// Code generated by tygo. DO NOT EDIT.

//////////
// source: protocol.go
/*
Package protocol defines the messages exchanged between UI clients and the
Engine over the control socket. TypeScript types are generated from this
package with tygo, so every exported type here is part of the wire contract.
*/

/**
 * Subprotocol is the WebSocket subprotocol a client must offer on the
 * control socket. The client also offers TokenSubprotocolPrefix followed by
 * the Engine's token, because browsers cannot set headers on WebSockets.
 */
export const Subprotocol = "hukube.v1";
/**
 * Subprotocol is the WebSocket subprotocol a client must offer on the
 * control socket. The client also offers TokenSubprotocolPrefix followed by
 * the Engine's token, because browsers cannot set headers on WebSockets.
 */
export const TokenSubprotocolPrefix = "hukube.token.";
/**
 * ClientType identifies what a ClientMessage asks the Engine to do.
 */
/**
 * ClientTypeRequest asks for a single response.
 */
export const ClientTypeRequest = "request";
/**
 * ClientTypeSubscribe starts a subscription that emits data until cancelled.
 */
export const ClientTypeSubscribe = "subscribe";
/**
 * ClientTypeUpdate replaces the params of an existing subscription, such as
 * when a list scrolls to a new window.
 */
export const ClientTypeUpdate = "update";
/**
 * ClientTypeUnsubscribe cancels a subscription.
 */
export const ClientTypeUnsubscribe = "unsubscribe";
export type ClientType = typeof ClientTypeRequest | typeof ClientTypeSubscribe | typeof ClientTypeUpdate | typeof ClientTypeUnsubscribe;
/**
 * ClientMessage is sent from a UI client to the Engine. ID is chosen by the
 * client and correlates responses and subscription data.
 */
export interface ClientMessage {
  id: number /* uint64 */;
  type: ClientType;
  method?: Method;
  params?: unknown;
}
/**
 * ServerType identifies the kind of ServerMessage.
 */
/**
 * ServerTypeResult answers a request.
 */
export const ServerTypeResult = "result";
/**
 * ServerTypeData carries the latest value of a subscription.
 */
export const ServerTypeData = "data";
/**
 * ServerTypeError reports a failed request or subscription.
 */
export const ServerTypeError = "error";
export type ServerType = typeof ServerTypeResult | typeof ServerTypeData | typeof ServerTypeError;
/**
 * ServerMessage is sent from the Engine to a UI client.
 */
export interface ServerMessage {
  id: number /* uint64 */;
  type: ServerType;
  data?: unknown;
  error?: ErrorDetail;
}
/**
 * ErrorCode classifies an ErrorDetail.
 */
export const ErrorCodeBadRequest = "bad_request";
export const ErrorCodeNotFound = "not_found";
export const ErrorCodeForbidden = "forbidden";
export const ErrorCodeInternal = "internal";
export type ErrorCode = typeof ErrorCodeBadRequest | typeof ErrorCodeNotFound | typeof ErrorCodeForbidden | typeof ErrorCodeInternal;
/**
 * ErrorDetail describes why a request or subscription failed.
 */
export interface ErrorDetail {
  code: ErrorCode;
  message: string;
}
/**
 * Method names a request or subscription topic.
 */
/**
 * MethodClustersList returns []Cluster.
 */
export const MethodClustersList = "clusters.list";
/**
 * MethodClusterStatus subscribes with ClusterParams to ClusterStatus.
 */
export const MethodClusterStatus = "cluster.status";
/**
 * MethodClusterTypes subscribes with ClusterParams to []ResourceType.
 */
export const MethodClusterTypes = "cluster.types";
/**
 * MethodResourcesQuery subscribes with QueryParams to QueryResult.
 */
export const MethodResourcesQuery = "resources.query";
/**
 * MethodResourceGet subscribes with ResourceRef to ResourceData.
 */
export const MethodResourceGet = "resource.get";
/**
 * MethodSettingsWatch subscribes with SettingKey to Setting.
 */
export const MethodSettingsWatch = "settings.watch";
/**
 * MethodSettingsPut stores a Setting and returns nothing.
 */
export const MethodSettingsPut = "settings.put";
export type Method = typeof MethodClustersList | typeof MethodClusterStatus | typeof MethodClusterTypes | typeof MethodResourcesQuery | typeof MethodResourceGet | typeof MethodSettingsWatch | typeof MethodSettingsPut;
/**
 * Cluster is one kubeconfig context the Engine can connect to.
 */
export interface Cluster {
  /**
   * ID is the kubeconfig context name.
   */
  id: string;
  server: string;
  user: string;
  namespace?: string;
  /**
   * Current reports whether this is the kubeconfig's current context.
   */
  current: boolean;
}
/**
 * ClusterParams selects a Cluster.
 */
export interface ClusterParams {
  cluster: string;
}
/**
 * ClusterPhase is the connection state of a Cluster.
 */
export const ClusterPhaseConnecting = "connecting";
export const ClusterPhaseReady = "ready";
export const ClusterPhaseFailed = "failed";
export type ClusterPhase = typeof ClusterPhaseConnecting | typeof ClusterPhaseReady | typeof ClusterPhaseFailed;
/**
 * ClusterStatus reports the Engine's connection to a Cluster.
 */
export interface ClusterStatus {
  phase: ClusterPhase;
  message?: string;
  serverVersion?: string;
}
/**
 * TypeKey identifies a Resource Type independently of API version, in
 * kubectl's "resource.group" form, such as "deployments.apps". Core types
 * have no group suffix, such as "pods".
 */
export type TypeKey = string;
/**
 * TypeState is the Engine's indexing state for a Resource Type.
 */
export const TypeStateSyncing = "syncing";
export const TypeStateReady = "ready";
export const TypeStateForbidden = "forbidden";
export const TypeStateFailed = "failed";
export type TypeState = typeof TypeStateSyncing | typeof TypeStateReady | typeof TypeStateForbidden | typeof TypeStateFailed;
/**
 * ResourceType is a Resource Type served by a Cluster, with the number of
 * Resources the Engine currently indexes for it.
 */
export interface ResourceType {
  key: TypeKey;
  group: string;
  version: string;
  resource: string;
  kind: string;
  namespaced: boolean;
  verbs: string[];
  shortNames?: string[];
  categories?: string[];
  state: TypeState;
  count: number /* int */;
}
/**
 * ExprOp is the operator of a query Expr.
 */
export const ExprOpAnd = "and";
export const ExprOpOr = "or";
export const ExprOpNot = "not";
/**
 * ExprOpIn matches when the field equals any of Values.
 */
export const ExprOpIn = "in";
/**
 * ExprOpContains matches when the field contains Values[0],
 * case-insensitively.
 */
export const ExprOpContains = "contains";
export type ExprOp = typeof ExprOpAnd | typeof ExprOpOr | typeof ExprOpNot | typeof ExprOpIn | typeof ExprOpContains;
/**
 * Field is a Resource attribute a query Expr can test.
 */
export const FieldType = "type";
export const FieldNamespace = "namespace";
export const FieldName = "name";
export type Field = typeof FieldType | typeof FieldNamespace | typeof FieldName;
/**
 * Expr is a Query expression tree. Logical operators use Args; comparison
 * operators use Field and Values.
 */
export interface Expr {
  op: ExprOp;
  field?: Field;
  values?: string[];
  args?: Expr[];
}
/**
 * SortField is a column a query result can be sorted by.
 */
export const SortFieldName = "name";
export const SortFieldNamespace = "namespace";
export const SortFieldAge = "age";
export type SortField = typeof SortFieldName | typeof SortFieldNamespace | typeof SortFieldAge;
/**
 * Sort orders a query result.
 */
export interface Sort {
  field: SortField;
  desc?: boolean;
}
/**
 * QueryParams subscribes to one window of the Resources matching a Query.
 * A nil Where matches every Resource.
 */
export interface QueryParams {
  cluster: string;
  where?: Expr;
  sort: Sort;
  offset: number /* int */;
  limit: number /* int */;
}
/**
 * QueryResult is one window of a query's matching Resources.
 */
export interface QueryResult {
  total: number /* int */;
  offset: number /* int */;
  rows: Row[];
}
/**
 * Row summarizes one Resource in a query result.
 */
export interface Row {
  uid: string;
  type: TypeKey;
  namespace?: string;
  name: string;
  createdAt: string;
}
/**
 * ResourceRef addresses one Resource in a Cluster. Namespace is empty for
 * cluster-scoped Resources.
 */
export interface ResourceRef {
  cluster: string;
  type: TypeKey;
  namespace?: string;
  name: string;
}
/**
 * ResourceData is the latest full Manifest of a Resource, as JSON.
 */
export interface ResourceData {
  object?: { [key: string]: unknown };
  deleted?: boolean;
}
/**
 * SettingKey selects a stored setting.
 */
export interface SettingKey {
  key: string;
}
/**
 * Setting is a stored JSON value. A missing setting has a null Value.
 */
export interface Setting {
  key: string;
  value: unknown;
}
